; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

;build_src_filter= +<main.cpp> 
;build_src_filter= +<01.setup.cpp> 
;build_src_filter= +<02.serial.cpp>
;build_src_filter= +<03.datawrite.cpp>
;build_src_filter= +<04.1byte_char_read.cpp>
;build_src_filter= +<05.readstring.cpp>
;build_src_filter= +<06.LEDonoff_char_write.cpp>
;build_src_filter= +<07.pinmode.cpp>
;build_src_filter= +<08.softwarePWM_basic.cpp>
build_src_filter= +<09.LED_smooth_fade.cpp>